### ISSUE TITLE
Error when using the gem with latest version of RSpec (3.2)

### ISSUE THREAD

**Issue by mpahuja** [allure-framework/allure-rspec#44]
Here is the error that we get with the latest version of rspec-core - 3.2.

```
C:/Ruby193/lib/ruby/gems/1.9.1/gems/allure-rspec-0.6.8/lib/allure-rspec/hooks.rb:18:in `block in hooks': undefined method `[]' for #<AllureRSpec::Hooks::OverrideHooksMethods::OverridenHookCollections:0x35e6ad0> (NoMethodError)
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/allure-rspec-0.6.8/lib/allure-rspec/hooks.rb:17:in `each'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/allure-rspec-0.6.8/lib/allure-rspec/hooks.rb:17:in `hooks'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:198:in `before'
	from c:/jenkins_slave/workspace/WSBNDRubySmoke/spec/integration/smoke_text_spec.rb:9:in `block in <top (required)>'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:363:in `module_exec'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:363:in `subclass'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:253:in `block in define_example_group_method'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
	from c:/jenkins_slave/workspace/WSBNDRubySmoke/spec/integration/smoke_text_spec.rb:3:in `<top (required)>'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `load'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `each'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:97:in `setup'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:85:in `run'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:70:in `run'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:38:in `invoke'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-3.2.0/exe/rspec:4:in `<top (required)>'
	from C:/Ruby193/bin/rspec:23:in `load'
	from C:/Ruby193/bin/rspec:23:in `<main>'
```

**Comment by smecsia** [comment]
@mpahuja It seems that RSpec guys have refactored their internal API. I will investigate this and fix as soon as I have more free time.

**Comment by haridak** [comment]
I see the same error.  Tentative ETA of the fix, please?

**Comment by smecsia** [comment]
@haridak I'll fix this in a day. Stay connected :)

**Comment by smecsia** [comment]
@mpahuja @haridak I've just bushed `0.6.9` version of `allure-rspec` into rubygems. Please check that the problem is fixed.
