### ISSUE TITLE
stack-trace is not clear:with inner rspec lib stack-trace in the head.

### ISSUE THREAD

**Issue by wuhuizuo** [allure-framework/allure-rspec#67]
# Given the rspec script:

``` ruby
require_relative 'spec_helper' #allure-rspec included.

describe 'zwh' do
   it 'hello' do
     expect(2).to eq(3)
   end
end
```
# Then got the report xml's partial content:

``` xml
<failure>
        <message>
expected: 3
     got: 2

(compared using ==)
</message>
        <stack-trace>/var/lib/gems/2.1.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:86:in `block in &lt;module:Support&gt;'&#xD;
/var/lib/gems/2.1.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `call'&#xD;
/var/lib/gems/2.1.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `notify_failure'&#xD;
/var/lib/gems/2.1.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/fail_with.rb:27:in `fail_with'&#xD;
/var/lib/gems/2.1.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:38:in `handle_failure'&#xD;
/var/lib/gems/2.1.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'&#xD;
/var/lib/gems/2.1.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'&#xD;
/var/lib/gems/2.1.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'&#xD;
/var/lib/gems/2.1.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/expectation_target.rb:54:in `to'&#xD;
/home/wuhuizuo/apps/vmp4-0/src/spec/zwh_spec.rb:5:in `block (2 levels) in &lt;top (required)&gt;'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `instance_exec'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `block in run'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `block in run'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `run'&#xD;
/var/lib/gems/2.1.0/gems/allure-rspec-0.7.4/lib/allure-rspec/hooks.rb:33:in `run'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `with_around_example_hooks'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:203:in `run'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:559:in `block in run_examples'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `map'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `run_examples'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:521:in `run'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `map'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'&#xD;
/var/lib/gems/2.1.0/gems/rspec-core-3.3.2/exe/rspec:4:in `&lt;top (required)&gt;'&#xD;
/usr/local/bin/rspec:23:in `load'&#xD;
/usr/local/bin/rspec:23:in `&lt;main&gt;'</stack-trace>
      </failure>
```
# But expected first stack-trace line is:

`/home/wuhuizuo/apps/vmp4-0/src/spec/zwh_spec.rb:5:in`block (2 levels) in &lt;top (required)&gt;'&#xD;`
# If use the origin rspec gem, the first line of stack-trace is the expected line:

`/home/wuhuizuo/apps/vmp4-0/src/spec/zwh_spec.rb:5:in`block (2 levels) in &lt;top (required)&gt;'&#xD;`

**Comment by smecsia** [comment]
@wuhuizuo This is a known issue related to the RSpec feature called [backtrace_exclusion_patterns](https://www.relishapp.com/rspec/rspec-core/docs/configuration/excluding-lines-from-the-backtrace). RSpec has its own exception formatter, which excludes some backtrace lines when it displays them in console. Allure-rspec takes the original exception and just passes it to allure-ruby-adapter-api, where backtrace is then rendered to xml.  There is no backtrace lines filtering for now. But I agree, it might be reasonable to implement it.
